<script setup>
import { computed, onMounted, ref } from 'vue'
import { get, patch, post, remove } from '../api/client'
import StateMessage from '../components/StateMessage.vue'

const section = ref('notes')
const notes = ref([]); const items = ref([]); const categories = ref([]); const tags = ref([]); const settings = ref(null)
const loading = ref(true); const error = ref(''); const message = ref('')
const editingNoteId = ref(null); const editingItemId = ref(null); const posterFile = ref(null)
const blankNote = () => ({ title: '', content_raw: '', content_format: 'markdown', started_at: new Date().toISOString().slice(0, 16), ended_at: '', visibility: 'private', static_path: '', category_id: '', secondary_categories: [], item_ids: [], context_label: '', progress_text: '', tag_ids: [] })
const noteForm = ref(blankNote())
const blankItem = () => ({ category_id: '', title: '', subtitle: '', creator: '', visibility: 'private', metadata_json_text: '{}' })
const itemForm = ref(blankItem())
const tagName = ref(''); const categoryName = ref(''); const categoryParent = ref('')
const roots = computed(() => categories.value.filter(c => c.is_root))

async function load() {
  loading.value = true; error.value = ''
  try {
    const [n, i, c, t, s] = await Promise.all([get('/api/manage/notes'), get('/api/manage/items'), get('/api/manage/categories'), get('/api/manage/tags'), get('/api/manage/settings')])
    notes.value = n.items; items.value = i.items; categories.value = c.items; tags.value = t.items; settings.value = s
    if (!noteForm.value.category_id) noteForm.value.category_id = roots.value.find(c => c.code === 'JOURNAL')?.id || roots.value[0]?.id
    if (!itemForm.value.category_id) itemForm.value.category_id = roots.value[0]?.id
    if (!categoryParent.value) categoryParent.value = roots.value[0]?.id
  } catch (err) { error.value = err.status === 401 ? 'Please sign in first.' : err.message } finally { loading.value = false }
}
function localInput(value) { if (!value) return ''; const date = new Date(value); const pad = n => String(n).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}` }
function resetNote() { editingNoteId.value = null; noteForm.value = blankNote(); if (roots.value.length) noteForm.value.category_id = roots.value.find(c => c.code === 'JOURNAL')?.id || roots.value[0].id }
function editNote(note) { editingNoteId.value = note.id; noteForm.value = { ...blankNote(), title: note.title, content_raw: note.content_raw, content_format: note.content_format, started_at: localInput(note.started_at), ended_at: localInput(note.ended_at), visibility: note.visibility, static_path: note.static_path || '', category_id: note.categories.find(c => c.is_primary)?.id || roots.value[0]?.id, secondary_categories: note.categories.filter(c => !c.is_primary).map(c => c.id), item_ids: note.items.map(item => item.id), context_label: note.items[0]?.context_label || '', progress_text: note.items[0]?.progress_text || '', tag_ids: note.tags.map(tag => tag.id) } }
async function saveNote() {
  error.value = ''
  try {
    const categoryIds = [Number(noteForm.value.category_id), ...noteForm.value.secondary_categories.map(Number)].filter(Boolean)
    const payload = { title: noteForm.value.title, content_raw: noteForm.value.content_raw, content_format: noteForm.value.content_format, started_at: new Date(noteForm.value.started_at).toISOString(), ended_at: noteForm.value.ended_at ? new Date(noteForm.value.ended_at).toISOString() : null, visibility: noteForm.value.visibility, static_path: noteForm.value.static_path || null, categories: categoryIds.map((id, index) => ({ category_id: id, is_primary: index === 0 })), items: noteForm.value.item_ids.map(id => ({ item_id: Number(id), context_label: noteForm.value.context_label || null, progress_text: noteForm.value.progress_text || null })), tag_ids: noteForm.value.tag_ids.map(Number) }
    if (editingNoteId.value) await patch(`/api/manage/notes/${editingNoteId.value}`, payload); else await post('/api/manage/notes', payload)
    message.value = editingNoteId.value ? 'Note updated' : 'Note created'; resetNote(); await load()
  } catch (err) { error.value = err.message }
}
async function deleteNote(id) { if (!window.confirm('Delete this Note permanently?')) return; try { await remove(`/api/manage/notes/${id}`); message.value = 'Note deleted'; await load() } catch (err) { error.value = err.message } }

function editItem(item) { editingItemId.value = item.id; itemForm.value = { category_id: item.category_id, title: item.title, subtitle: item.subtitle, creator: item.creator, visibility: item.visibility, metadata_json_text: JSON.stringify(item.metadata_json || {}, null, 2) } }
function resetItem() { editingItemId.value = null; itemForm.value = blankItem(); if (roots.value.length) itemForm.value.category_id = roots.value[0].id; posterFile.value = null }
async function saveItem() {
  try {
    const metadata_json = JSON.parse(itemForm.value.metadata_json_text || '{}'); const payload = { category_id: Number(itemForm.value.category_id), title: itemForm.value.title, subtitle: itemForm.value.subtitle, creator: itemForm.value.creator, metadata_json }
    const result = editingItemId.value ? await patch(`/api/manage/items/${editingItemId.value}`, payload) : await post('/api/manage/items', { ...payload, visibility: itemForm.value.visibility })
    if (posterFile.value) { const response = await fetch(`/api/manage/items/${result.id}/poster`, { method: 'PUT', credentials: 'same-origin', headers: { 'Content-Type': posterFile.value.type }, body: posterFile.value }); if (!response.ok) throw new Error('poster upload failed') }
    message.value = editingItemId.value ? 'Item updated' : 'Item created'; resetItem(); await load()
  } catch (err) { error.value = err.message || 'metadata must be valid JSON' }
}
async function deleteItem(id) { if (!window.confirm('Delete this Item and its links permanently?')) return; try { await remove(`/api/manage/items/${id}`); message.value = 'Item deleted'; await load() } catch (err) { error.value = err.message } }
async function toggleItem(item) { try { await post(`/api/manage/items/${item.id}/visibility`, { visibility: item.visibility === 'public' ? 'private' : 'public' }); await load() } catch (err) { error.value = err.message } }
async function publishItemNotes(item) { try { const result = await post(`/api/manage/items/${item.id}/notes/set-public`, {}); message.value = `Published ${result.updated_count}; ${result.blocked_count} blocked`; await load() } catch (err) { error.value = err.message } }
async function createTag() { try { await post('/api/manage/tags', { name: tagName.value }); tagName.value = ''; await load() } catch (err) { error.value = err.message } }
async function editTag(tag) { const name = window.prompt('Tag name', tag.name); if (name && name !== tag.name) { try { await patch(`/api/manage/tags/${tag.id}`, { name }); await load() } catch (err) { error.value = err.message } } }
async function deleteTag(id) { if (window.confirm('Delete this tag?')) { try { await remove(`/api/manage/tags/${id}`); await load() } catch (err) { error.value = err.message } } }
async function createCategory() { try { await post('/api/manage/categories', { name: categoryName.value, parent_id: Number(categoryParent.value) }); categoryName.value = ''; await load() } catch (err) { error.value = err.message } }
async function editCategory(category) { const name = window.prompt('Category name', category.name); if (name && name !== category.name) { try { await patch(`/api/manage/categories/${category.id}`, { name }); await load() } catch (err) { error.value = err.message } } }
async function deleteCategory(id) { if (window.confirm('Delete this category?')) { try { await remove(`/api/manage/categories/${id}`); await load() } catch (err) { error.value = err.message } } }
async function saveSettings() { try { await patch('/api/manage/settings', settings.value); message.value = 'Settings saved' } catch (err) { error.value = err.message } }
onMounted(load)
</script>

<template>
  <section class="manage-page"><div class="section-heading"><div class="eyebrow mono">CONTROL / PRIVATE</div><h1>Archive desk</h1><p class="muted">Changes are server-validated and visible only to the administrator.</p></div>
    <StateMessage v-if="loading" type="loading" message="Opening control surface…" /><p v-if="error" class="inline-error" role="alert">{{ error }}</p><p v-if="message" class="success-message" role="status">{{ message }}</p>
    <template v-if="!loading"><div class="manage-tabs"><button v-for="name in ['notes','items','taxonomy','settings']" :key="name" :class="{ active: section === name }" @click="section = name">{{ name.toUpperCase() }}</button></div>
      <div v-if="section === 'notes'" class="manage-grid"><form class="editor-card" @submit.prevent="saveNote"><h2>{{ editingNoteId ? 'Edit Note' : 'New Note' }}</h2><label>Title<input v-model="noteForm.title" maxlength="200"></label><label>Started at<input v-model="noteForm.started_at" type="datetime-local" required></label><label>Ended at<input v-model="noteForm.ended_at" type="datetime-local"></label><label>Primary category<select v-model="noteForm.category_id" required><option v-for="category in categories" :key="category.id" :value="category.id">{{ category.name }}</option></select></label><label>Secondary categories<select v-model="noteForm.secondary_categories" multiple><option v-for="category in categories" :key="category.id" :value="category.id">{{ category.name }}</option></select></label><label>Items<select v-model="noteForm.item_ids" multiple><option v-for="item in items" :key="item.id" :value="item.id">{{ item.title }}</option></select></label><label>Item context<input v-model="noteForm.context_label" maxlength="200"></label><label>Progress<input v-model="noteForm.progress_text" maxlength="200"></label><label>Tags<select v-model="noteForm.tag_ids" multiple><option v-for="tag in tags" :key="tag.id" :value="tag.id">#{{ tag.name }}</option></select></label><label>Static HTML path<input v-model="noteForm.static_path" placeholder="pages/example.html"></label><label>Format<select v-model="noteForm.content_format"><option value="markdown">Markdown</option><option value="html">HTML</option></select></label><label>Visibility<select v-model="noteForm.visibility"><option value="private">Private</option><option value="public">Public</option></select></label><label>Content<textarea v-model="noteForm.content_raw" rows="10"></textarea></label><div class="button-row"><button class="primary-button">{{ editingNoteId ? 'UPDATE NOTE' : 'SAVE NOTE' }}</button><button v-if="editingNoteId" type="button" class="link-button" @click="resetNote">CANCEL</button></div></form><div><h2>Notes</h2><div v-for="note in notes" :key="note.id" class="admin-row"><span class="mono">{{ note.archive_label }}</span><span>{{ note.title || 'Untitled event' }}</span><span class="muted">{{ note.visibility }}</span><button class="link-button" @click="editNote(note)">EDIT</button><button class="danger-button" @click="deleteNote(note.id)">DELETE</button></div></div></div>
      <div v-else-if="section === 'items'" class="manage-grid"><form class="editor-card" @submit.prevent="saveItem"><h2>{{ editingItemId ? 'Edit Item' : 'New Item' }}</h2><label>Category<select v-model="itemForm.category_id" required><option v-for="root in roots" :key="root.id" :value="root.id">{{ root.name }}</option></select></label><label>Title<input v-model="itemForm.title" required maxlength="200"></label><label>Subtitle<input v-model="itemForm.subtitle"></label><label>Creator<input v-model="itemForm.creator"></label><label>Visibility<select v-model="itemForm.visibility"><option value="private">Private</option><option value="public">Public</option></select></label><label>Metadata JSON<textarea v-model="itemForm.metadata_json_text" rows="6" spellcheck="false"></textarea></label><label>Poster (JPEG/PNG/WebP, 5 MiB)<input type="file" accept="image/jpeg,image/png,image/webp" @change="posterFile = $event.target.files[0] || null"></label><div class="button-row"><button class="primary-button">{{ editingItemId ? 'UPDATE ITEM' : 'SAVE ITEM' }}</button><button v-if="editingItemId" type="button" class="link-button" @click="resetItem">CANCEL</button></div></form><div><h2>Items</h2><div v-for="item in items" :key="item.id" class="admin-row"><span>{{ item.title }}</span><span class="muted">{{ item.visibility }}<small v-if="item.private_note_count"> · {{ item.private_note_count }} private notes</small></span><button class="link-button" @click="toggleItem(item)">{{ item.visibility === 'public' ? 'MAKE PRIVATE' : 'PUBLISH' }}</button><button v-if="item.visibility === 'public' && item.private_note_count" class="link-button" @click="publishItemNotes(item)">PUBLISH NOTES</button><button class="link-button" @click="editItem(item)">EDIT</button><button class="danger-button" @click="deleteItem(item.id)">DELETE</button></div></div></div>
      <div v-else-if="section === 'taxonomy'" class="manage-grid"><div class="editor-card"><h2>New tag</h2><form @submit.prevent="createTag"><label>Name<input v-model="tagName" required></label><button class="primary-button">ADD TAG</button></form><h2>New child category</h2><form @submit.prevent="createCategory"><label>Root<select v-model="categoryParent" required><option v-for="root in roots" :key="root.id" :value="root.id">{{ root.name }}</option></select></label><label>Name<input v-model="categoryName" required></label><button class="primary-button">ADD CATEGORY</button></form></div><div><h2>Tags</h2><div v-for="tag in tags" :key="tag.id" class="admin-row"><span>#{{ tag.name }}</span><span class="mono">{{ tag.slug }}</span><button class="link-button" @click="editTag(tag)">EDIT</button><button class="danger-button" @click="deleteTag(tag.id)">DELETE</button></div><h2>Categories</h2><div v-for="category in categories" :key="category.id" class="admin-row"><span>{{ category.name }}</span><span class="mono">{{ category.code }}</span><template v-if="!category.is_root"><button class="link-button" @click="editCategory(category)">EDIT</button><button class="danger-button" @click="deleteCategory(category.id)">DELETE</button></template></div></div></div>
      <form v-else class="editor-card settings-form" @submit.prevent="saveSettings"><h2>Site settings</h2><label>Title<input v-model="settings.site_title"></label><label>Tagline<input v-model="settings.site_tagline"></label><label>Timezone<input v-model="settings.timezone"></label><label>NOW status<input v-model="settings.now_status"></label><label>About format<select v-model="settings.about_format"><option value="markdown">Markdown</option><option value="html">HTML</option></select></label><label>About<textarea v-model="settings.about_raw" rows="10"></textarea></label><label>Current Note ID<input v-model.number="settings.current_note_id" type="number" min="1"></label><button class="primary-button">SAVE SETTINGS</button></form>
    </template>
  </section>
</template>
